version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
      args:
        - HTTP_PROXY=${COMMON_HTTP_PROXY}
        - HTTPS_PROXY=${COMMON_HTTPS_PROXY}
        - WORK_DIR=${GO_WORK_DIR}
    container_name: cli
    tty: true
    environment:
      - HTTP_PROXY=${COMMON_HTTP_PROXY}
      - HTTPS_PROXY=${COMMON_HTTPS_PROXY}
