version: '3'
services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      args:
        - HTTP_PROXY=${COMMON_HTTP_PROXY}
        - HTTPS_PROXY=${COMMON_HTTPS_PROXY}
        - WORK_DIR=${GO_WORK_DIR}
    container_name: go
    tty: true
    volumes:
      - ./:${GO_WORK_DIR}
    environment:
      - HTTP_PROXY=${COMMON_HTTP_PROXY}
      - HTTPS_PROXY=${COMMON_HTTPS_PROXY}
