version: '3'
services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - work_dir=${WORK_DIR}
    container_name: go
    tty: true
    volumes:
      - ./:${WORK_DIR}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
