qiita:
  user: hello
  password: world
  login_url: https://qiita.com/login
tasks:
  - url: https://qiita.com/
    xpath: //a[@class='tr-Item_title']
  - url: https://qiita.com/
    xpath: //a[@class='tr-Item_title']
